

services: 
  postgres:
    build:
      context: .
      dockerfile: .docker/dev/postgres.Dockerfile
    
    restart: always
    tty: true
   
    ports:
      - "5432:5432"
    volumes:
      - .docker/volumes/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
 


  pgadmin:
    image: dpage/pgadmin4
    
    restart: always
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8000:80"
    volumes:
      - .docker/volumes/pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres
   