

services:
  app:
    build: 
     context: .
     dockerfile: .docker/prod/Dockerfile
    container_name: app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

 