



services:
   postgres:
     image: postgres:16.4-alpine3.20
     container_name: postgres
     user: postgres
     restart: always
     environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
     ports:
      - 5432:5432
     volumes:
      - .docker/dev/volumes/postgres:/var/lib/postgresql/data

   pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    user: root
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8000:80
    volumes:
      - .docker/dev/volumes/pgadmin:/var/lib/pgadmin


networks:
  local-network:
    driver: bridge
   